name: e_shop
description: Flutter eCommerce App using Firebase Firestore from Clothify

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:
  cloud_firestore: ^0.13.2+1
  lottie:
  image_picker: ^0.6.3+1
  google_maps_flutter: ^0.5.21
  path_provider: ^2.0.3
  flutter_staggered_grid_view: ^0.4.0
  cupertino_icons: ^1.0.2
  provider: ^4.0.4
  carousel_pro: ^0.0.13
  transparent_image: ^2.0.0
  font_awesome_flutter: ^9.1.0
  shared_preferences: ^0.5.6+1
  fluttertoast: ^8.0.8
  flutter_spinkit: ^4.1.2+1
  firebase_database:
  image: ^2.0.7
  intl:
  uuid:
  http:
  badges: ^2.0.1
  firebase_storage: ^3.1.1
  firebase_auth:
  firebase_core: ^0.4.0
  url:
  firebase:
  firebase_analytics:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

  assets:
    - images/logo1.png
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png
    - images/
    - images/5A.jpg



